version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambdaurl"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ydje3focfuj5"
s3_prefix = "lambdaurl"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
